# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Envelope

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DataObject(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DataObject()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDataObject(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DataObject
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DataObject
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DataObject
    def Xml(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def DataObjectStart(builder):
    builder.StartObject(2)

def Start(builder):
    DataObjectStart(builder)

def DataObjectAddType(builder, type):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(type), 0)

def AddType(builder, type):
    DataObjectAddType(builder, type)

def DataObjectAddXml(builder, xml):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(xml), 0)

def AddXml(builder, xml):
    DataObjectAddXml(builder, xml)

def DataObjectEnd(builder):
    return builder.EndObject()

def End(builder):
    return DataObjectEnd(builder)
