# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Envelope

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ForwardMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ForwardMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsForwardMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ForwardMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ForwardMessage
    def Key(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ForwardMessage
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ForwardMessage
    def PipelineInfo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Envelope.PipelineInformation import PipelineInformation
            obj = PipelineInformation()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ForwardMessage
    def Informations(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Envelope.Information import Information
            obj = Information()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ForwardMessage
    def InformationsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ForwardMessage
    def InformationsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def ForwardMessageStart(builder):
    builder.StartObject(4)

def Start(builder):
    ForwardMessageStart(builder)

def ForwardMessageAddKey(builder, key):
    builder.PrependUint64Slot(0, key, 0)

def AddKey(builder, key):
    ForwardMessageAddKey(builder, key)

def ForwardMessageAddTimestamp(builder, timestamp):
    builder.PrependUint64Slot(1, timestamp, 0)

def AddTimestamp(builder, timestamp):
    ForwardMessageAddTimestamp(builder, timestamp)

def ForwardMessageAddPipelineInfo(builder, pipelineInfo):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(pipelineInfo), 0)

def AddPipelineInfo(builder, pipelineInfo):
    ForwardMessageAddPipelineInfo(builder, pipelineInfo)

def ForwardMessageAddInformations(builder, informations):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(informations), 0)

def AddInformations(builder, informations):
    ForwardMessageAddInformations(builder, informations)

def ForwardMessageStartInformationsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartInformationsVector(builder, numElems):
    return ForwardMessageStartInformationsVector(builder, numElems)

def ForwardMessageEnd(builder):
    return builder.EndObject()

def End(builder):
    return ForwardMessageEnd(builder)
