# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Envelope

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Information(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Information()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInformation(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Information
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Information
    def TotalFrameCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Information
    def TotalFrameDuration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Information
    def FrameIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Information
    def FrameTimestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Information
    def DataObject(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Envelope.DataObject import DataObject
            obj = DataObject()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def InformationStart(builder):
    builder.StartObject(5)

def Start(builder):
    InformationStart(builder)

def InformationAddTotalFrameCount(builder, totalFrameCount):
    builder.PrependUint64Slot(0, totalFrameCount, 0)

def AddTotalFrameCount(builder, totalFrameCount):
    InformationAddTotalFrameCount(builder, totalFrameCount)

def InformationAddTotalFrameDuration(builder, totalFrameDuration):
    builder.PrependFloat32Slot(1, totalFrameDuration, 0.0)

def AddTotalFrameDuration(builder, totalFrameDuration):
    InformationAddTotalFrameDuration(builder, totalFrameDuration)

def InformationAddFrameIndex(builder, frameIndex):
    builder.PrependUint64Slot(2, frameIndex, 0)

def AddFrameIndex(builder, frameIndex):
    InformationAddFrameIndex(builder, frameIndex)

def InformationAddFrameTimestamp(builder, frameTimestamp):
    builder.PrependFloat32Slot(3, frameTimestamp, 0.0)

def AddFrameTimestamp(builder, frameTimestamp):
    InformationAddFrameTimestamp(builder, frameTimestamp)

def InformationAddDataObject(builder, dataObject):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(dataObject), 0)

def AddDataObject(builder, dataObject):
    InformationAddDataObject(builder, dataObject)

def InformationEnd(builder):
    return builder.EndObject()

def End(builder):
    return InformationEnd(builder)
