# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Envelope

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PipelineInformation(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PipelineInformation()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPipelineInformation(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PipelineInformation
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PipelineInformation
    def FrameCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def PipelineInformationStart(builder):
    builder.StartObject(1)

def Start(builder):
    PipelineInformationStart(builder)

def PipelineInformationAddFrameCount(builder, frameCount):
    builder.PrependUint64Slot(0, frameCount, 0)

def AddFrameCount(builder, frameCount):
    PipelineInformationAddFrameCount(builder, frameCount)

def PipelineInformationEnd(builder):
    return builder.EndObject()

def End(builder):
    return PipelineInformationEnd(builder)
